### ISSUE TITLE
Server to Server OAuth

### ISSUE THREAD

**Issue by create** [asimlqt/php-google-spreadsheet-client#105]
I am trying to authenticate with a Service Account. I am receiving permission denied responses (401). Is this type of auth not supported?

**Comment by asimlqt** [comment]
Yes, service account is supported. I have successfully used this in then past. If you supply the code you are using I might be able to help.

**Comment by asimlqt** [comment]
@create - You opened this issue quite a while back now, I'm assuming you've solved it so closing this ticket.
