### ISSUE TITLE
getListFeed() stops reading on empty row

### ISSUE THREAD

**Issue by nekromoff** [asimlqt/php-google-spreadsheet-client#107]
e.g. read everything until row 97, row 97 is empty/blank, but row 98 continues with data.
However getListFeed() return only all the rows until this blank row.

**Comment by asimlqt** [comment]
This is not a bug in this library, it's how Google spreadsheet api works. Please see the following for further info: https://developers.google.com/google-apps/spreadsheets/?hl=en
