### ISSUE TITLE
Multiple rows insert

### ISSUE THREAD

**Issue by dneykov** [asimlqt/php-google-spreadsheet-client#108]
Hi everybody,
I have to insert more then 4000 rows in google spreadsheet, currently I'm trying to loop through each and do $listFeed->insert($row);
But it's inserting around 1000 rows and getting Internal Server Error. Can somebody help? Is it possible to make it work with this library?
Thanks in advance.

**Comment by dneykov** [comment]
Issue can be closed, [this](https://github.com/asimlqt/php-google-spreadsheet-client/issues/66) really help me

**Comment by asimlqt** [comment]
I'm glad it helped.
