### ISSUE TITLE
Reduce Time

### ISSUE THREAD

**Issue by MULLAINATHAN** [asimlqt/php-google-spreadsheet-client#114]
Hi All,
I have 40,000 rows. When I try to insert, it took long time (~ 30 minutes). 
Is it possible to reduce insertion time. 
Please help me.

**Comment by Dartui** [comment]
I guess that there is no way to reduce time, but there are two ways to insert data:
1. slower: https://github.com/asimlqt/php-google-spreadsheet-client#adding-a-list-row
2. faster: https://github.com/asimlqt/php-google-spreadsheet-client#updating-multiple-cells-with-a-batch-request

If you are using first, try to change it to 2nd.
