### ISSUE TITLE
in SpreadsheetFeed.php : add getByID($FileID)

### ISSUE THREAD

**Issue by MilkTeaD** [asimlqt/php-google-spreadsheet-client#118]
/**
     * by id
     */
    public function getById($Id)
    {
       $idstring="https://spreadsheets.google.com/feeds/spreadsheets/private/full/$Id";
       foreach($this->xml->entry as $entry) {
           if ($entry->id->__toString() == $idstring) {
                return new Spreadsheet($entry);
           }
       }
       return null;
    }

**Comment by asimlqt** [comment]
Thanks.
