### ISSUE TITLE
oAuth 2.0 code with service account

### ISSUE THREAD

**Issue by MilkTeaD** [asimlqt/php-google-spreadsheet-client#120]
create a service account
download the JSON file
    
    require 'vendor/autoload.php';
    $clientId='<blablabla>';
    $clientEmail='<yourserviceaccount>@<yourapp>.iam.gserviceaccount.com';
    $client = new Google_Client();
    putenv("GOOGLE_APPLICATION_CREDENTIALS=<path><jsonauthfile>.json");
    $client->useApplicationDefaultCredentials();

    $client->setApplicationName("<YOURAPP>"); // Don't miss this one !!!!
    $client->setScopes(['https://www.googleapis.com/auth/drive','https://spreadsheets.google.com/feeds']);

    if ($client->isAccessTokenExpired()) {
        $client->refreshTokenWithAssertion();
    };

    $tokenArray=$client->fetchAccessTokenWithAssertion();
    $accessToken=$tokenArray["access_token"];

et voilà

**Comment by iTsFILIPOficial** [comment]
Do he need any extra dependencies ? Like google client api?

**Comment by GustavoA23** [comment]
This method worked for me on the initial attempt. However the next time I attempted to run my php I received this Error

PHP Fatal error:  Uncaught exception 'Google\Spreadsheet\UnauthorizedException' with message 'You need permission' in /var/www/html/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php:282

**Comment by iTsFILIPOficial** [comment]
@GustavoA23 Did you allow the application to access the spreadsheet?

**Comment by GustavoA23** [comment]
Yes, I was able to post into my spreadsheet the first time. My spreadsheet is published to web

**Comment by asimlqt** [comment]
"Published to the web" means that it's publicly accessible. i.e. it doesn't require an OAuth token.

See the section on how to access public spreadsheets in the [README](https://github.com/asimlqt/php-google-spreadsheet-client#retrieving-a-public-spreadsheet)

NB. Only available in version 3+
