### ISSUE TITLE
HTTP: 400 error on $listfeed->insert($row);

### ISSUE THREAD

**Issue by GustavoA23** [asimlqt/php-google-spreadsheet-client#125]
Around 30 minutes ago (Without any changes to my code). Suddenly every attempt to insert a row returns a http 400 error code, Everything prior to inserting works fine (pulling list feed and getting values out of a spreadsheet).

**Comment by MaxZhuravlev** [comment]
Please check my issue - i think it linked to yours https://github.com/asimlqt/php-google-spreadsheet-client/issues/124

**Comment by hokage4** [comment]
i'm beginner in php, plz can tell me step by step how u can insert into google spreadsheet 
i try many time but i failed

**Comment by asimlqt** [comment]
@GustavoA23 Is this still an issue?

If so can you paste an example of your code that fails?
