### ISSUE TITLE
Can not use sq parameter to filter by date

### ISSUE THREAD

**Issue by malbalat85** [asimlqt/php-google-spreadsheet-client#126]
I want to use the sq parameter to filter some rows by date, but it doesn't work at all. I search the API and see that you pass it to the getListFeed function as an `array('sq' => 'date>3/2/2016')` but it doesn't work. Even if you want to filter using text way the only way to make it work it's like this `array('sq' => 'texttofind=="searchtext"')` and if you find [google doc](https://developers.google.com/google-apps/spreadsheets/#sending_a_structured_query_for_rows) there is no mention about this. There is another way to make such thing?

Thanks in advance

**Comment by asimlqt** [comment]
I've just tested the following and it works fine:
$listFeed = $worksheet->getListFeed(["sq" => "age > 20 and age < 30"]);

I'm not sure how i handles dates, you maybe better of using timestamps instead.
