### ISSUE TITLE
API Key instead OAuth

### ISSUE THREAD

**Issue by michelem09** [asimlqt/php-google-spreadsheet-client#127]
Is there a way to use an API Key (Server key) instead the OAuth authentication?

**Comment by asimlqt** [comment]
No there isn't.

I think what you're asking is if you can make requests directly without any user involvement or without authenticating on behalf of a user? If so have a look at the documentation for [Service Accounts](https://developers.google.com/identity/protocols/OAuth2ServiceAccount)

Either way you will end up with an OAuth token which you need to use with this library.
