### ISSUE TITLE
Children: list

### ISSUE THREAD

**Issue by mazedulislamkhan** [asimlqt/php-google-spreadsheet-client#128]
Hi,
Is there any built-in method available for getting everything under a folder. Google have the [Children: list](https://developers.google.com/drive/v2/reference/children/list#request) API point to get this.

**Comment by asimlqt** [comment]
Hi, I'm assuming the Google Drive PHP SDK has support for that. This project uses the Spreadsheet API which has nothing to do with Drive so unfortunately this is not possible.
