### ISSUE TITLE
getListFeed by cell or column?

### ISSUE THREAD

**Issue by mazedulislamkhan** [asimlqt/php-google-spreadsheet-client#130]
Hi,
I just wanted to know if is there any method or way to get the list feed by specifying a cell or column? The getCell() method isn't working for me and can't find any documentation that says about the getCell() method. Please, can anyone help?

**Comment by asimlqt** [comment]
Hi,
I'm not sure what you mean, can you provide a sample spreadsheet with an example of what you're trying to achieve?

A list feed returns an array for each row in the spreadsheet. You can't retrieve a list feed from a cell.

**Comment by mazedulislamkhan** [comment]
Apologies if the above message doesn't make sense. I would just like to get content from specific column/cell. In that case, how may I achieve this?

**Comment by asimlqt** [comment]
If you want to get a specific cell then use CellFeed, you can get any cell in the worksheet.

There is no  builtin way to retrieve a column so you'll just have to iterate over the List feed and get the value  of that cell.
