### ISSUE TITLE
$listFeed->getEntries() gets  data only before blank row

### ISSUE THREAD

**Issue by Krispian** [asimlqt/php-google-spreadsheet-client#134]
Hello! 
In my document data formatting empty rows, z try get all my data width $listFeed->getEntries() but get only first 10 rows (11 row is empty). How I get other 1000 rows?

**Comment by asimlqt** [comment]
Hi,

You can't have blank rows.

[https://developers.google.com/google-apps/spreadsheets/#retrieving_a_list-based_feed](https://developers.google.com/google-apps/spreadsheets/#retrieving_a_list-based_feed)
