### ISSUE TITLE
Sorry, unable to open the file at this time

### ISSUE THREAD

**Issue by insaneDev** [asimlqt/php-google-spreadsheet-client#135]
I got an error when trying to add sheet headers.

`
$worksheet = $worksheetFeed->getByTitle('Sheet1');

$cellFeed = $worksheet->getCellFeed();

$cellFeed->editCell(1,1, "Row1Col1Header");

$cellFeed->editCell(1,2, "Row1Col2Header");
`

**Sorry, unable to open the file at this time**

Does anyone have any clues?

**Comment by asimlqt** [comment]
I just tried the above and it's working for me. It could have been a temporary glitch.

Is it working for you now?

**Comment by zohaib055** [comment]
I am having the same issue not resolved yet
