### ISSUE TITLE
Editing data from Public Spreadsheet

### ISSUE THREAD

**Issue by flo62134** [asimlqt/php-google-spreadsheet-client#139]
Hi everyone,

I created a public spreadsheet, allowed it to be edited and seen by everybody.
I succeeded in retrieving data but I can't manage to edit data...

This is my code

`<?php

require 'vendor/autoload.php';
use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;
use Google\Spreadsheet\SpreadSheetService;

$serviceRequest = new DefaultServiceRequest("");
ServiceRequestFactory::setInstance($serviceRequest);

$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$worksheetFeed = $spreadsheetService->getPublicSpreadsheet('1t5dQFkMafnjHaynHyiH970PWIJO1Jlp2SrDG-AJzXy8');

$worksheet = $worksheetFeed->getByTitle('Feuille 1');

$cellFeed = $worksheet->getCellFeed();
$cell = $cellFeed->getCell(2,2);
$cell->update("Yop");`

And this is the result : 

Fatal error: Uncaught exception 'Google\Spreadsheet\Exception\BadRequestException' with message '<!DOCTYPE html><html lang="en" ><head><meta name="description" content="Web word processing, presentations and spreadsheets"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=0"><link rel="shortcut icon" href="//ssl.gstatic.com/docs/common/drive_favicon1.ico"><title>Google Drive -- Page Not Found</title><link href="//fonts.googleapis.com/css?family=Product+Sans" rel="stylesheet" type="text/css"><style>/\* Copyright 2016 Google Inc. All Rights Reserved. _/ .goog-inline-block{position:relative;display:-moz-inline-box;display:inline-block}_ html .goog-inline-block{display:inline}*:first-child+html .goog-inline-block{display:inline}#drive-logo{margin:18px 0;position:absolute;white-space:nowrap}.docs-drivelogo-img{background-image:url('//ssl.gstatic.com/images/branding/googlelogo/1x/googlelogo_color_116x41dp.png');background-size:116px 41px;display:inline-block; in C:\xampp\htdocs\google\vendor\asimlqt\php-google-spreadsheet-client\src\Google\Spreadsheet\DefaultServiceRequest.php on line 359

The error code is 405.

Thank you for your help !

**Comment by dilab** [comment]
@flo62134 how did you solve this?
