### ISSUE TITLE
Usage issue

### ISSUE THREAD

**Issue by answer3** [asimlqt/php-google-spreadsheet-client#145]
Hello there
In Example, I have PUBLIC link to document "https://docs.google.com/spreadsheets/d/{some_id}/edit#gid=0"
How to retrieve data from this document?
Your library send requests to "https://spreadsheets.google.com/"
Thanks

**Comment by asimlqt** [comment]
[https://github.com/asimlqt/php-google-spreadsheet-client#retrieving-a-public-spreadsheet](https://github.com/asimlqt/php-google-spreadsheet-client#retrieving-a-public-spreadsheet)
