### ISSUE TITLE
Style Cell

### ISSUE THREAD

**Issue by hampusboas** [asimlqt/php-google-spreadsheet-client#147]
Hello,
Thank you for this awesome repo!
Is there anyway to style a cell with font-weight or background-color?

**Comment by asimlqt** [comment]
Hi @hampusboas

Not as far as I'm aware.

**Comment by hampusboas** [comment]
Ok. 
Thank you for the fast reply.
Have a nice day

**Comment by ankitdhanna007** [comment]
I wanted it too !
Any possible way ?

**Comment by asimlqt** [comment]
Not with the version this library uses.

The new version (V4) allows you to do this but you'll have to use the official Google PHP SDK for that.

**Comment by driade** [comment]
Hi @asimlqt Could you give an example please? Thanks in advance.
