### ISSUE TITLE
String could not be parsed as XML because no connection

### ISSUE THREAD

**Issue by jfrac** [asimlqt/php-google-spreadsheet-client#148]
We're using [v2.3.7](https://github.com/asimlqt/php-google-spreadsheet-client/releases/tag/2.3.7)

Sometimes, we get "String could not be parsed as XML" error. When print de output of curl from DefaultServiceRequest, we get this:

    Error Number: 7
    Error String:Failed to connect to 2a00:1450:4007:808::200e: The network is inaccessible

We don't know if that is due connection, the version we use, a problem with IPv6 o what.

Thanks in advantage.

**Comment by asimlqt** [comment]
Hi @jfrac 

If you only get it sometimes then it most likely won't be this library, it will be a network issue on your end.

**Comment by jfrac** [comment]
@asimlqt thx!
