### ISSUE TITLE
Usage within Laravel

### ISSUE THREAD

**Issue by nekromoff** [asimlqt/php-google-spreadsheet-client#180]
in the code:
```
use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;
```

but getting:
` (1/1) FatalThrowableError
Class 'App\Providers\Google\Spreadsheet\DefaultServiceRequest' not found`

**Comment by paulchill** [comment]
put the \ before Google

   $spreadsheetService = new \Google\Spreadsheet\SpreadsheetService();
