### ISSUE TITLE
getSpreadsheets() returns empty list

### ISSUE THREAD

**Issue by Schepp** [asimlqt/php-google-spreadsheet-client#22]
Hey Asim, thank you for putting that much effort into this thing!

Still, I've got to report a problem. I think I got everything set up correctly, but when I want to retrieve the list of spreadsheets located under my account all I get is an empty list. On the other hand, when I'm logged into Google and open https://spreadsheets.google.com/feeds/spreadsheets/private/full in the browser I **do** see an extensive list of documents. Any idea why that is? I published the spreadsheet and I also set it to publicly visible, but no luck...

Here is my code:

``` php
<?php

// Config
require_once __DIR__ . '/../config.php';

// Autoload Composer packages
require __DIR__ . '/../vendor/autoload.php';

use Google\Spreadsheet\DefaultServiceRequest;
use Google\Spreadsheet\ServiceRequestFactory;

$client = new Google_Client();
$client->setApplicationName('My Webservice');
$client->setClientId(GOOGLE_CLIENTID);

$cred = new Google_Auth_AssertionCredentials(
    GOOGLE_CLIENTEMAIL,
    array('https://spreadsheets.google.com/feeds'),
    file_get_contents(GOOGLE_CLIENTKEYPATH)
);

$client->setAssertionCredentials($cred);

if($client->getAuth()->isAccessTokenExpired()) {
    $client->getAuth()->refreshTokenWithAssertion($cred);
}

$obj_token  = json_decode($client->getAccessToken());
$accessToken = $obj_token->access_token;

$serviceRequest = new DefaultServiceRequest($accessToken);
ServiceRequestFactory::setInstance($serviceRequest);

$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$spreadsheetFeed = $spreadsheetService->getSpreadsheets();
```

Thank you in advance for your help!

**Comment by alfiebesin** [comment]
I know this is a bit old but might help someone who faces the same issue. You just need to share the spreadsheet to your service account email so it will be able to lists it. Thanks
