### ISSUE TITLE
getByID missing

### ISSUE THREAD

**Issue by johnh530** [asimlqt/php-google-spreadsheet-client#26]
I had used a previous version of this project (looks like I downloaded it may 6 2013).  I used getByID to retrieve both spreadsheets and worksheets.  It appears with the current version there is only getByTitle.

It would be nice to be able to retrieve by ID as well as name.  I believe it is possible to have two different spreadsheets/worksheets with the Title.

It would be nice to have this functionality back in place.
johnh...

**Comment by erikverheij** [comment]
Perhaps you can add this example to the readme; 

```
$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$spreadsheet = $spreadsheetService->getSpreadsheetById('key');
```
