### ISSUE TITLE
Get cell formula instead of calculated value

### ISSUE THREAD

**Issue by jeffrigby** [asimlqt/php-google-spreadsheet-client#30]
Is it possible to get a cell's formula instead of the calculated value? I can't seem to find a way to do this.

Some background: I'd like the ability to clone a worksheet. I can easily create a new worksheet and enter all the values based on a cellFeed but I'm unable to extract the formula string from the cellFeed.

**Comment by Loschcode** [comment]
could you answer to this please ? it's been 1 year it's waiting and i'm wondering too.

**Comment by Loschcode** [comment]
I went in the source code of this package and it doesn't seem it ever access the formula whatsoever. It's very weird to let people add rows, edit values, check everything and even add sheets but not let the access to the value ...

Answer needed here ... I really need this functionality, i'd fork the project but i don't quite understand where it could be catch.

**Comment by asimlqt** [comment]
You need to extract the cell entries from the cell feed (CellFeed::getEntries()) and on the CellEntry there is a method called 'getInputValue' which will return the formula of the cell.
