### ISSUE TITLE
Regarding Google Docs redirects...

### ISSUE THREAD

**Issue by ethanclevenger91** [asimlqt/php-google-spreadsheet-client#31]
Occasionally Google drops a 302 redirect when navigating around Google Docs, including on requests (like curl). See:

https://productforums.google.com/forum/#!topic/docs/vGn7eN-zznw
http://stackoverflow.com/questions/5834821/read-csv-fails-to-read-a-csv-file-from-google-docs

It doesn't happen consistently, but on occasion. This library throws an exception when it happens here:

    if($httpCode > 299) {
            if($httpCode === 401) {
                throw new UnauthorizedException('Access token is invalid', 401);
            } else {
                throw new Exception('Error in Google Request', $info['http_code']);
            }
        }

To get around this, I'm doing a brute force retry, but this doesn't seem like a great solution:

    protected function execute($ch)
    {
        $httpCode = '';
        while($httpCode == '' || $httpCode == 302) {
            if($httpCode == 302) {
                echo 'Redirected before completion<br>';
            }
            $ret = curl_exec($ch);

            $info = curl_getinfo($ch);
            $httpCode = (int)$info['http_code'];
        }
        if($httpCode > 299) {
            if($httpCode === 401) {
                throw new UnauthorizedException('Access token is invalid', 401);
            } else {
                throw new Exception('Error in Google Request', $info['http_code']);
            }
        }

        return $ret;
    }

This works well enough, outputting the diagnostic a couple of times for a set of about 100 items, but there has to be a better solution. Found some article saying that the 302 response should include a URL parameter called `gsession`, which is how it authenticates the redirect and seems to prevent a simple `CURLOPT_FOLLOWLOCATION => 1` from solving the issue. Could be that adding this parameter to the `PUT` request on 302 responses might solve it? Haven't had time to implement it, but I'll update if I get it functioning.

**Comment by dawez** [comment]
Having the same issue, sometimes got a redirect from google which caused and error. Ended up using  a retry in the DefaultServiceRequest:

```php
protected function execute($ch)
    {
        $retry_max = 3;
        $retry_count = 1;
        $response_success = false;

        while ($retry_count < $retry_max and $response_success == false) {
            $ret = curl_exec($ch);
            $info = curl_getinfo($ch);
            $httpCode = (int) $info['http_code'];

            if ($httpCode > 299) {
                $retry_count ++;
            } else {
                $response_success = true;
            }
        }

        if ($response_success == false && $httpCode > 299) {
            if ($httpCode === 401) {
                throw new UnauthorizedException('Access token is invalid', 401);
            } else {
                throw new Exception('Error in Google Request', $info['http_code']);
            }
        }
        return $ret;
    }
```

**Comment by Remiii** [comment]
I'm getting the same error :cry:

**Comment by mattimatti** [comment]
Same error here, 2% of failures trying to update publicly editable spreadsheets.

**Comment by asimlqt** [comment]
I've set curl to follow redirects now, hopefully this will fix it.

If not then I might have to apply a fix similar to @Remiii

**Comment by asimlqt** [comment]
Assuming the "follow location headers" has fixed this issue since no one has reported any further issues for a while so I'm closing this issue.
