### ISSUE TITLE
Batch update blank cells

### ISSUE THREAD

**Issue by jeffrigby** [asimlqt/php-google-spreadsheet-client#32]
Is there a way to batch update blank cells? updateBatch() seems to work fine if the cells have existing content and are therefore are returned in CellFeed(), but it the cells are not in the CellFeed, I'm unable to create an new entry. Currently I'm checking if the cell exists in the CellFeed and if it isn't, I call editCell(). This works fine but it creates another API call. I'd like to handle this all in one batch request.

Is there a way to manually create a cellEntry to pass to addEntry()?

``` php
    // $data is in format: array('A1' => 'value1', 'B2' => 'value2')
    foreach ($data as $pos => $value) {
      // Convert position key from sheet format to indexes A2 => 1, 2
      $pos = $this->convertAlphaNumPos($pos);
      $input = $cell_feed->getCell($pos['row'], $pos['col']);
      if (empty($input)) {
        // CellEntry doesn't exist. Use edit cell.
        $cell_feed->editCell($pos['row'], $pos['col'], $value);
      }
      else {
        $input->setContent($value);
        $batch_request->addEntry($input);
      }
    }

    $cell_feed->updateBatch($batch_request);
```

**Comment by j0rd** [comment]
It appears Spreadsheet->addWorksheet('Name', $row, $col); also doesn't create a bunch of blank cells with IDs either.

So that removes a simple way of bulk editing with out hitting the API too much as well, correct?
