### ISSUE TITLE
Service Account Access

### ISSUE THREAD

**Issue by machadoug** [asimlqt/php-google-spreadsheet-client#36]
Greetings,

This is not really an issue, more like a question regarding Service Account Access.
Can you provide an example on how to use this php-google-spreadsheet-client with Service Account Access?

I've downloaded the Google APIs Client Library for PHP and I got the service-account.php example working, but I could not manage to get it working with the Spreadsheet  example provided.

I'm trying to accomplish the same thing we had with the zend_Gdata, adding a new row for each form submission in our site.

Thanks in advanced for your help.

**Comment by SimonEast** [comment]
I have created a wiki page which explains how to do this.  Hope that helps others.  :-)

https://github.com/asimlqt/php-google-spreadsheet-client/wiki/How-to-use-%22Service-account%22-authorization-(rather-than-user-based-access-refresh-tokens)

**Comment by qualutions** [comment]
Thanks a ton for the wiki page solved my problem.

**Comment by axelwehner** [comment]
Thanks @SimonEast. That helped me a lot.

**Comment by samoum23** [comment]
hello guys i used the same code of @ZurabWSG but i obtain this error 
Error refreshing the OAuth2 token, message: '{
"error" : "invalid_client",
"error_description" : "The OAuth client was invalid."
}' 

this is my code 

 $client = new \Google_Client();
    $client->setClientId("irresistible@irresi-1349.iam.gserviceaccount.com");

    
    $key = file_get_contents("../app/config/google.p12");
    $cred = new \Google_Auth_AssertionCredentials(
        'drax.simplyguardian@gmail.com',
        array('https://spreadsheets.google.com/feeds'),
        $key
    );

    $client->setAssertionCredentials($cred);

    if($client->getAuth()->isAccessTokenExpired()) {
        $client->getAuth()->refreshTokenWithAssertion($cred);
    }

    $service_token = json_decode($client->getAccessToken());
    return $service_token->access_token;
    die;

plz help guys
