### ISSUE TITLE
$listEntry->update very slow

### ISSUE THREAD

**Issue by kvasko** [asimlqt/php-google-spreadsheet-client#47]
Hello,

Yesterday I created a new script which is updating a certain cells in the specific rows. This script search the rows - which have to update - based on the value of the id column. The script is working but I have 2 problems with it.
1. Because I have to always feed (get) the specific row what I would like to update. This process takes ages.
2. (I think) Because of the above problem some times later I am getting error message during this process. 

This is my update script:
$listFeed2 = $worksheet->getListFeed(array("sq" => "id = ".$val_R['id']));
$entries = $listFeed2->getEntries();
$listEntry = $entries[0];
$values = $listEntry->getValues();
$values['counts'] = $count;
$values['host'] = $host2;
$values['service'] = $service2;
$values['alarm'] = $type2;
$values['date'] = $time;
$values['statusinformation'] = $information;
$values['status'] = $status_R;
$listEntry->update($values);

Is there any way to create this script easier and faster? Is it any possibility to update the cells of the specific row without always feeding the worksheet to speed up this process?

Unfortunately I didn't find any solution till now, but for me is very important to solve this issue asap.

Thank you for your answer in advance!

BR,
Krisztián

**Comment by asimlqt** [comment]
Hi,

You can use batch requests to update mutliple cells in one request. Have a look at CellFeed::updateBatch().  You'll need to get the worksheet in this case but you can update as many cells as you want in one request, it's the best way of updating multiple cells.

If you want to quickly update a single cell you can create a new class which extends CellEntry and overrides the constructor, and use that to update the cell you want. This way you'll make a request to google for every request so if you're updating multiple cells it will be slow!

You'll also need to save the postUrl somewhere so you can reuse it. You can get the post url by doing the following.

$postUrl = $worksheet->getCellFeed()->getPostUrl();

You'll need to create the following class:

class MyCellEntry extends \Google\Spreadsheet\CellEntry {
    public function __construct($postUrl, $row, $col) {
        $this->postUrl = $postUrl;
        $this->row = $row;
        $this->column = $column;
    }
}

// You can then use it like:

ServiceRequestFactory::setInstance(new DefaultServiceRequest($accessToken));
$cellEntry = new MyCellEntry("http://post-url....", 3, 4);
$cellEntry->update("hello");


Hope that helps

**Comment by kvasko** [comment]
Hello, 

What you described above is excellent and the performance of the query process is much better than before. I can use it, but I have one BIG problem what I can't figure out. Earlier with Zend package I have got the number of the rows based on the id value which is the value of the first column. 
$listFeed2 = $worksheet->getListFeed(array("sq" => "id = ".$val_R['id']));

Now with this update what you described above I have the col number and postURL, but I haven't got the number of the row. Can I get this number anyhow easier not to update all rows only those where the id is matching with my findings?

$cellEntry = new MyCellEntry("http://post-url....", ?, 4); 

? = the row numbers where the values of the ids are present

Thanks for your help in advance!

BR,
Krisztián

**Comment by kvasko** [comment]
Hello Again,

It seems I figured out how it works. I created an array. VALUE = value of the cell of the first (id) column + KEY = row number:
$cellFeed = $worksheet->getCellFeed();

foreach($cellFeed->getEntries() as $cellEntry) {
  $row = $cellEntry->getRow();
  $col = $cellEntry->getColumn();
  $val = $cellEntry->getContent();
    if ($col == "1"){
        $row_array[$row] = $val;
    }
}

After with array_search I got the number of the row based on the given value(id):
$row = array_search($id, $row_array);

With this row number I was able to start the BATCH update....

BR,
Krisztián
