### ISSUE TITLE
Blank row in Google Sheet causes issue

### ISSUE THREAD

**Issue by thephm** [asimlqt/php-google-spreadsheet-client#49]
Sorry if this is a known limitation but I had a google sheet where the first row is a header row, second row is empty, and then there were 50 rows with data. When I used the list feed it was empty. 

Similarly, if there is a blank row within the sheet only the rows above the blank row are in the list feed, none beyond the blank row.

This would be a major limitation. Shouldn't the list feed just include the blank rows with empty cell values to represent what is in the sheet. Worst case, skip the blank rows.

Thanks for taking a look!

**Comment by asimlqt** [comment]
This is not a limitation of this library but of the Google Spreadsheet API itself.

"The list feed contains all rows after the first row up to the first blank row. The first blank row terminates the data set. If expected data isn't appearing in a feed, check the worksheet manually to see whether there's an unexpected blank row in the middle of the data. In particular, if the second row of the spreadsheet is blank, then the list feed will contain no data."

https://developers.google.com/google-apps/spreadsheets/
