### ISSUE TITLE
( ! ) Warning: array_combine(): Both parameters should have an equal number of elements in /netapp/home/rdempsey/public_html/SurveyAutomation/src/Google/Spreadsheet/ListFeed.php on line 109

### ISSUE THREAD

**Issue by SgtPooki** [asimlqt/php-google-spreadsheet-client#6]
My code is as follows:

```
$request = new Google\Spreadsheet\Request($accessObj->access_token);
$serviceRequest = new Google\Spreadsheet\DefaultServiceRequest($request);
Google\Spreadsheet\ServiceRequestFactory::setInstance($serviceRequest);
$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$spreadsheetFeed = $spreadsheetService->getSpreadsheets();
$spreadsheet = $spreadsheetFeed->getByTitle('COPY Survey Document');
$worksheetFeed = $spreadsheet->getWorksheets();

foreach($worksheetFeed as $worksheet) {
    var_dump($worksheet->getTitle());
    $listFeed = $worksheet->getListFeed();
    $entries = $listFeed->getEntries();
    foreach($entries as $entry) {
        $rowHash = $entry->getValues();
        if(!array_key_exists('sendsurvey', $rowHash)) {
            break 1;
        }
        var_dump($rowHash);
    }
}
```

And the code throwing the above error in listFeed is 
        $entries = $listFeed->getEntries();

I double checked and the cols had 1 less item in the array than the vals, but can we suppress this error or handle it more cleanly? I don't know what the best solution would be right now.

**Comment by ZurabWSG** [comment]
There are cases when a column name is empty and there's a value in a cell in that column. That's when this error is thrown. In my case, the cell only contained a space character. This simple fix worked for me. I added the following code to line #107 of ListFeed.php:


				
				if(count($colNames) != count($vals) && count($colNames) < count($vals)) {
					while(trim(end($vals)) == '' && count($colNames) < count($vals)) {
						array_pop($vals);
					}
				}
