### ISSUE TITLE
Feature: direct call to listfeed in specific worksheet

### ISSUE THREAD

**Issue by rodekker** [asimlqt/php-google-spreadsheet-client#65]
Hi,

I already know the id of the spreadsheet and the id of the worksheet. Would it be possible to implement a function to execute the listfeed on the basis of the id of the spreadsheet and the id of the worksheet.

Saves a few API-calls to the Google-backends and consequently time.

--Roel

**Comment by asimlqt** [comment]
Hi,

Not currently.  Yes it would definitely save some API calls and speed things up, I'll have a look into this when i have some time.

Asim

**Comment by asimlqt** [comment]
Hi Roel,

I have added support for this, see commit https://github.com/asimlqt/php-google-spreadsheet-client/commit/474a429ef09e7b9301779fa4641021cb87f0311b

Tagged with: 2.3.4

Asim

**Comment by rodekker** [comment]
Much appreciated!

On 12 April 2015 at 18:22, Asim Liaquat <notifications@github.com> wrote:

> Hi Roel,
>
> I have added support for this, see commit 474a429
> <https://github.com/asimlqt/php-google-spreadsheet-client/commit/474a429ef09e7b9301779fa4641021cb87f0311b>
>
> Tagged with: 2.3.4
>
> Asim
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asimlqt/php-google-spreadsheet-client/issues/65#issuecomment-92085151>
> .
>



-- 
--Roel
