### ISSUE TITLE
Method to insert multiple rows

### ISSUE THREAD

**Issue by SimonEast** [asimlqt/php-google-spreadsheet-client#66]
Is there a way to insert multiple rows at a time?  Currently calling `$listFeed->insert()` makes a HTTP request for each row which is terribly slow if needing to insert multiple.

Or is this something I could perhaps submit a pull request for?

**Comment by asimlqt** [comment]
Yes there is, have a look at the following commit:
https://github.com/asimlqt/php-google-spreadsheet-client/commit/f1042119c1662c885125a4dc4b9e83299e74afe6

**Comment by MULLAINATHAN** [comment]
Hi I need to insert multiple rows. I want know how to use Batch.? 
Is anybody have sample code.? 
Please help me.

**Comment by asimlqt** [comment]
I've added an example to the README file:
https://github.com/asimlqt/php-google-spreadsheet-client#updating-multiple-cells-with-a-batch-request
