### ISSUE TITLE
The library will broken with the "Document List API" deprecation ?

### ISSUE THREAD

**Issue by gustavobgama** [asimlqt/php-google-spreadsheet-client#69]
As anunced [here](http://googleappsupdates.blogspot.com.br/2015/03/final-reminder-deprecated-google-apps.html) the **document list API** will no longer available from **april 20th**.

And I received from Google an email notifying me that I need to search for requests for those URLs in my apps:
* https://docs.google.com/feeds/
* https://docs.googleusercontent.com/
* https://spreadsheets.google.com/feeds/

And migrate to [Google Drive API](https://developers.google.com/drive/web/migration#migrating_from_the_documents_list_api). BTW in the previous link, there is the warning:

> "The Drive API v2 is built on Google's new JSON-based API infrastructure, which is not backward compatible with the XML-based Documents List API v3."

And I see in code that the library relies on **XML format**.

The library will broken after april 20th ?

**Comment by asimlqt** [comment]
This library Uses the spreadsheet API (https://developers.google.com/google-apps/spreadsheets/) and not Document List API so I'm sure it will be fine.

Thanks for the info anyway.

**Comment by gustavobgama** [comment]
Thanks for the response. Great to hear that !
