### ISSUE TITLE
How to use Google_Client and setAssertionCredentials to connect

### ISSUE THREAD

**Issue by sebastienhouzet** [asimlqt/php-google-spreadsheet-client#71]
Hello,

Is it possible to used server side connection and not AccessToken with you library ?
i see in your construct Token type (defaults to OAuth for BC).

if is possible, how use it ?

thx.

**Comment by Dartui** [comment]
This is my solution to connect by service and .json file to google sheets: https://github.com/asimlqt/php-google-spreadsheet-client/issues/110#issuecomment-159529461
