### ISSUE TITLE
New getListFeed in 2.3.4 works only on single sheets with gid=0

### ISSUE THREAD

**Issue by rodekker** [asimlqt/php-google-spreadsheet-client#76]
Hi,

The new 'shortcut' to get a listFeed ($listFeed= $spreadsheetService->getListFeed('SPREADSHEETID');) works fine, but the function assumes that the 'sheetId' is always '0', which is in most cases true, but sometimes it looks differently (example Google Drive "...edit#gid=1409838528"). And certainly if the spreadsheet contains multiple sheets.

Resolution would be to introduce a second (optional) parameter in the call, which contains the sheetId (if not '0')

--Roel

**Comment by asimlqt** [comment]
This method will be reworked in the next version since it's not reliable.
