### ISSUE TITLE
Edit publicly shared  spreadsheets

### ISSUE THREAD

**Issue by mattimatti** [asimlqt/php-google-spreadsheet-client#77]
Hello I'm trying to figure out how to edit publicly shared spreadsheets.

https://docs.google.com/spreadsheets/d/1I02bVK66ayVUKIzfHzEns2u0S-QozCEbCEPADrf1FJA/edit#gid=0

Is this possible with your library? Your authentication defaults to oauth.

        $serviceRequest = new Google\Spreadsheet\DefaultServiceRequest($accessToken);
        Google\Spreadsheet\ServiceRequestFactory::setInstance($serviceRequest);

But in my case i don't want the users to deal with access tokens.

Form the google docs i see that i could be able to access public data even with "Public API access"

https://developers.google.com/console/help/new/?hl=en_US#usingkeys

> Use an API key when your application is running on a server and accessing one of the following kinds > of data:

> Data that the data owner has identified as public, such as a public calendar or blog.
> Data that is owned by a Google service such as Google Maps or Google Translate. (Access limitations > may apply.)

Should I implement another class implementing your ServiceRequestInterface ?

Thank you in advance!

**Comment by mattimatti** [comment]
I've resolved setting up a "Service account"

**Comment by lucascampelo** [comment]
Can you explain who do it, @mattimatti ? I'm realy interested to retreaving and update a public shared spreadsheet but your comment hasn't so clear to me.

**Comment by tag** [comment]
I am also curious about how to do this. I'm not finding it in project the documentation.
