### ISSUE TITLE
editCell not support NEWLINE "\n" character

### ISSUE THREAD

**Issue by francescobianco** [asimlqt/php-google-spreadsheet-client#78]
this is a strange problem!!!

$feedCell->editCell(1,1,"Hello\nWorld");

in the Spreadsheet linebreak are stripped WHY????

**Comment by sirgod** [comment]
I wanted to use new lines so I found an workaround for this, use:

> ="hello"&CHAR(10)&"world"

But be careful when sending the data, make sure you escape the double quotes. See issue: 

https://github.com/asimlqt/php-google-spreadsheet-client/issues/82

**Comment by Dartui** [comment]
You can use CONCATENATE function, for example:
```
$feedCell->editCell(1,1,"=CONCATENATE('Hello'; CHAR(10); 'World')");
```

**Comment by asimlqt** [comment]
This has been resolved in the latest version. You can use "\n" when editing the cell content.
