### ISSUE TITLE
Unable to insert value in google spread sheet

### ISSUE THREAD

**Issue by sumitdevl** [asimlqt/php-google-spreadsheet-client#79]
Hello Sir,

I am trying to insert value but i am getting error. "Fatal error: Uncaught exception 'Google\Spreadsheet\Exception' with message 'Error in Google Request: The Doclist API has been shut down. Please use the new Drive API, https://developers.google.com/drive/." please solve this problem. thank you

**Comment by clumsydreams** [comment]
If you are passing key/value pairs("key" => "value") then you should use lowercase keys with no space between words.
For example: First Name should be typed as firstname.
