### ISSUE TITLE
Error when reading Google Sheet

### ISSUE THREAD

**Issue by XAMelleOH** [asimlqt/php-google-spreadsheet-client#81]
When trying to read this doc: https://docs.google.com/a/detto.com.ua/spreadsheet/lv?key=0AokYcCWjwZn_dHJFcXI0djZFdWNXT2Q0MmhzajVITWc&f=true&noheader=true&gid=0 I get an error (nothing displayed, 500 response code). About 20 other ones are ok.

I've discovered, the error is in getWorksheets(); and if more precisely in $worksheet->setPostUrl($this->getPostUrl()); of WorksheetFeed.php

I assume it can be because of using &trade; in the worksheet names, but not sure 100%.

**Comment by XAMelleOH** [comment]
Anyone working on this???

**Comment by asimlqt** [comment]
Thanks for supplying a sample sheet.

I've just tested this using the following code and it worked fine.

```php
$spreadsheetService = new Google\Spreadsheet\SpreadsheetService();
$spreadsheet = $spreadsheetService->getSpreadsheetById("1foXfuR0jNo3idUv3dKhH-Bh9yGV4SJ-ia14rMmHKoJw");
$feed = $spreadsheet->getWorksheets();
$ws = $feed->getByTitle("Кузя™ 2014");
var_dump($ws->getListFeed());
```
