### ISSUE TITLE
getByTitle() outputs mangled UTF-8?

### ISSUE THREAD

**Issue by nekromoff** [asimlqt/php-google-spreadsheet-client#85]
DarÄekovÃ© kÃ³dy
instead of Darčekové kódy

therefore I am unable to match correct UTF-8 and this function returns _null_.

**Comment by nekromoff** [comment]
fixed by adding this function so it's easy to fetch by spreadsheet URL / ID:

```
    /**
     * Gets a spreadhseet from the feed by its ID.
     *
     * @param string $title
     *
     * @return \Google\Spreadsheet\Spreadsheet|null
     */
    public function getByID($ID)
    {
        foreach($this->xml->entry as $entry) {
            if($entry->id->__toString() == $ID) {
                return new Spreadsheet($entry);
            }
        }
        return null;
    }
```

**Comment by asimlqt** [comment]
I've just tested this and it works fine:

$service = new SpreadsheetService();
$spreadsheetFeed = $service->getSpreadsheets();
$spreadsheet = $spreadsheetFeed->getByTitle("Darčekové kódy");
echo $spreadsheet->getTitle()."\n";

It outputs the title correctly in utf-8.

Also there is no need to fetch a list of spreadsheets if you know the id of the spreadsheet you want.

@see https://github.com/asimlqt/php-google-spreadsheet-client/blob/master/src/Google/Spreadsheet/SpreadsheetService.php#L50
