### ISSUE TITLE
Error in Google Request for Headers with spaces.

### ISSUE THREAD

**Issue by neiljun-odiaz** [asimlqt/php-google-spreadsheet-client#91]
I have a spreadsheet with a header of "Ph #" and when I try to add a new row, it returns this error:

Fatal error: Uncaught exception 'Google\Spreadsheet\Exception' with message 'Error in Google Request' in D:\xampp\htdocs\google-spreadsheet\src\Google\Spreadsheet\DefaultServiceRequest.php:256 Stack trace: #0 D:\xampp\htdocs\google-spreadsheet\src\Google\Spreadsheet\DefaultServiceRequest.php(152): Google\Spreadsheet\DefaultServiceRequest->execute(Resource id #52) #1 D:\xampp\htdocs\google-spreadsheet\src\Google\Spreadsheet\ListFeed.php(79): Google\Spreadsheet\DefaultServiceRequest->post('https://spreads...', '<entry xmlns="h...') #2 D:\xampp\htdocs\google-spreadsheet\index.php(71): Google\Spreadsheet\ListFeed->insert(Array) #3 {main} thrown in D:\xampp\htdocs\google-spreadsheet\src\Google\Spreadsheet\DefaultServiceRequest.php on line 256

**Comment by asimlqt** [comment]
Google does modify the header text when using the api so it won't be exactly the same as what you see in the web client. When you fetch the row data using this library, print out the data so you can see the exact headers that you need to supply.
