### ISSUE TITLE
How to move a sheet column or row to another sheet with in a spreadsheet

### ISSUE THREAD

**Issue by venkynani** [asimlqt/php-google-spreadsheet-client#99]
i just try this code and working good and now am try to move a sheet column or row from one sheet to another sheet any one please help me to find a solution and is there any way to apply sorting and formula for data validation. have any ideas just share with me please...

**Comment by asimlqt** [comment]
There is no easy way to move a column or row from one worksheet to another. You'll have to read the data from the sheet you want to copy from as a feed and create a batch request so you can upload it to the new sheet in a single request.

You can perform basic sorting when reading data form the google api, you can supply the sorting parameters when calling Worksheet::getListFeed and Worksheet::getCellFeed methods. See the official google spreadhsheet api docs for the valid params.

I don't quite understand your question regarding validation. you can validate the data in php however you want before uploading it to the new sheet.
